# Site wide configuration
title: My Blog
description: "My personal blog"
logo: Holly_Karushin.jpg # 120x120 px default image used for Twitter summary card
teaser: teaser_05.jpg # 400x250 px default teaser image used in image archive grid
locale: ru
url: http://kapb14.github.io

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner: 
  name: "Alexander Karushin"
  email: kapb14@gmail.com
  twitter: kapb14
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: Selfy1_Karushin_wrapped.jpg # 160x160 px image for author byline
  disqus-shortname: kapb14


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]












